/**
 * Some common outputting.
 */

// Dependencies
const chalk = require('chalk');

// Exports
module.exports = {
  welcome: function() {
    return (
      chalk.green(`
........................................
...................=....................
...................=....................
..................===...................
..................===...................
.................=====..................
.................=====..................
................=======.................
................=======.................
...............+=======~................
.=====================.000000000000000*.
...+================..00000000000000....
......============...000000000000.......
........========....00000000000.........
...........===.....000000000............
..................000000000.............
.................0000000000.............
...............0000000000000............
..............00000.00000000............
.............0000.....0000000...........
............000.........00000...........
...........00.............0000..........
..........0.................000.........
..............................0.........
........................................
`) +
      `
   ${chalk.bgGreen.black('                              ')}
   ${chalk.bgGreen.black('   ★ Striblab Generator ★     ')}
   ${chalk.bgGreen.black('                              ')}
` +
      chalk.cyan`
We're gonna create a new project from a template
in this directory. We need to get some info from
you first.

`
    );
  },

  done: function() {
    return `
   ${chalk.bgGreen.black('                              ')}
   ${chalk.bgGreen.black('       ★ We did it! ★         ')}
   ${chalk.bgGreen.black('                              ')}

Please read the ${chalk.yellow('README.md')} that was generated
in your new project for details on how the project is setup.

Run ${chalk.bgYellow.black(' gulp develop ')} to start developing.

Run ${chalk.bgYellow.black(' gulp tasks ')} to see the other available commands.

`;
  }
};
